"""expAK_loops.py — Entry 52: the obstruction is HOMOLOGICAL (positive theta around non-contractible loops).

Entry 51 reduced PB<1 on an all-ray Chern=-k line to: the difference constraints  y_t - y_s > theta_e
are consistent  <=>  no directed cycle has sum theta >= 0  (Karp max-mean-cycle mu* < 0).

KEY GEOMETRY (this entry): the competitor graph has FORWARD edges only -- (x,y)->(x+1,y) and (x,y)->(x,y+1)
(the Landau-gauge directed edges). On the torus every directed closed walk must therefore WRAP an integer
number of times in x and y: the directed cycle space is generated by the homology generators H_1(T^2).
Hence the positive-cycle obstruction is carried by a HOMOLOGICALLY NON-TRIVIAL loop -- the 'harmonic'
direction. So:
    PB>=1 (bound holds on an all-ray line)  <=>  some non-contractible directed loop C has sum_{e in C} theta_e >= 0.

Measured (m=6, all-ray Chern=-2): EVERY horizontal and vertical wrap-loop has sum theta > 0 (mu*=+1.81).
This script makes that reproducible: harvest an all-ray Chern=-k line, verify all-ray, compute theta_e,
the m horizontal + m vertical wrap-loop theta-sums, and Karp mu*. Writes loops.json.
Reuses expU/expAE/expAJ/expAI.
"""

from __future__ import annotations
import importlib.util, json, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
def _load(name, fn):
    spec = importlib.util.spec_from_file_location(name, os.path.join(HERE, fn))
    mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod); return mod
expU = _load("expU", "expU_shadow.py")
expAE = _load("expAE", "expAE_pq.py")
expAJ = _load("expAJ", "expAJ_phase_margin.py")
expAI = _load("expAI", "expAI_cycle.py")


def eidx(x, y, horiz, m):
    """index into the directed edge list (expU.edges order: per site, [H then V])."""
    return 2*((x % m)*m + (y % m)) + (0 if horiz else 1)


def find_all_ray_line(m, k, tries=40):
    src, dst = expAE.edge_idx(m, k); phi = np.array([e[2] for e in expU.edges(m, k)])
    best = None; bestwm = -np.inf
    for sd in range(tries):
        rng = np.random.default_rng(500+31*k+sd)
        u0 = expAE.project_unit(rng.standard_normal((m*m, 3)) + 1j*rng.standard_normal((m*m, 3)))
        wm, uf = expAJ.ascend(u0, src, dst, phi, steps=1500)
        ch = expAE.chern_of_u(m, uf)
        if ch is not None and abs(ch+k) < 0.4 and wm > bestwm:
            bestwm = wm; best = uf
    return best, src, dst, phi


def loop_analysis(u, src, dst, phi, m):
    thetas, kinds, _, _ = expAI.edge_thetas(u, src, dst, phi)
    allray = (kinds.count('ray') == len(kinds))
    Hsums = [float(sum(thetas[eidx(x, y, True, m)] for x in range(m))) for y in range(m)]
    Vsums = [float(sum(thetas[eidx(x, y, False, m)] for y in range(m))) for x in range(m)]
    mu = expAI.karp_max_mean_cycle(m*m, src, dst, thetas) if allray else None
    return dict(all_ray=allray, chern=round(expAE.chern_of_u(m, u), 2),
                H_min=round(min(Hsums), 3), H_max=round(max(Hsums), 3),
                V_min=round(min(Vsums), 3), V_max=round(max(Vsums), 3),
                all_H_pos=bool(all(h > 0 for h in Hsums)), all_V_pos=bool(all(v > 0 for v in Vsums)),
                mu_star=(round(float(mu), 4) if mu is not None else None))


def main():
    print("Entry 52: directed cycles on the torus are wraparounds (forward-edge graph) => the positive-")
    print("theta obstruction is HOMOLOGICAL. Measure wrap-loop theta-sums on all-ray Chern=-k lines.\n")
    out = {}
    for m, k in ((6, 2), (8, 2)):
        u, src, dst, phi = find_all_ray_line(m, k)
        if u is None:
            print(f"m={m} k={k}: no all-ray Chern=-{k} line found (handled by empty-edge Lemma 51 instead)")
            out[f"k{k}_m{m}"] = None; continue
        r = loop_analysis(u, src, dst, phi, m); out[f"k{k}_m{m}"] = r
        print(f"m={m} k={k}: Chern={r['chern']:+.1f} all-ray={r['all_ray']} mu*={r['mu_star']}")
        print(f"   horiz wrap-loop sum theta in [{r['H_min']:+.3f},{r['H_max']:+.3f}] (all>0: {r['all_H_pos']})")
        print(f"   vert  wrap-loop sum theta in [{r['V_min']:+.3f},{r['V_max']:+.3f}] (all>0: {r['all_V_pos']})")
        verdict = ("INFEASIBLE via a non-contractible loop (sum theta>=0) -> PB>=1 (bound holds)"
                   if (r['mu_star'] is not None and r['mu_star'] >= -1e-9) else "check")
        print(f"   => {verdict}\n")
    print("OPEN CORE (sharpened): for an all-ray Chern!=0 line, some non-contractible directed loop C has")
    print("sum_{e in C} theta_e >= 0.  theta_e=log x_e^0 is an explicit per-edge weight; the loop integral is")
    print("the holonomy. Measured: ALL wrap-loops strictly positive in the even-k all-ray case.")
    with open(os.path.join(HERE, "loops.json"), "w") as f: json.dump(out, f, indent=2)
    print("wrote loops.json")


if __name__ == "__main__":
    main()
